/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    YourContract: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_Owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "monto",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "Owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "Monto",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "ID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "pass",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "fixed_penalty",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "GracePeriod",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "Penalty_Percentage",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "Duration",
              type: "uint256",
            },
          ],
          name: "ContratoCreado",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_Propiedad",
              type: "uint256",
            },
          ],
          name: "AceptarContrato",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "Monto",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "allowedWallet",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_GracePeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_Penalty_Percentage",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_Duration",
              type: "uint256",
            },
          ],
          name: "CrearContrato",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_propiedad",
              type: "uint256",
            },
          ],
          name: "PagarAlquiler",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "accept",
              type: "bool",
            },
          ],
          name: "answerContractCancelationPropopsitionLease",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "accept",
              type: "bool",
            },
          ],
          name: "answerContractCancelationPropopsitionOwner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_Propiedad",
              type: "uint256",
            },
          ],
          name: "calcularMontoAPagar",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
          ],
          name: "cancelContractOwner",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "contractExists",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "contratosAlquiler",
          outputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "enum ContractStatus",
              name: "Status",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "Owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "Lesse",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "Monto",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "ID_propiedad",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "AllowedWallet",
              type: "address",
            },
            {
              internalType: "enum PenaltyType",
              name: "Penalty",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "PenaltyPercentage",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "GracePeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "DurationInMonths",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "TimestampLastPayment",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_Propiedad",
              type: "uint256",
            },
          ],
          name: "cuantosMesesAdeudo",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "last_timestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "today_timestamp",
              type: "uint256",
            },
          ],
          name: "cuantosMesesAdeudoTest",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_Id",
              type: "uint256",
            },
          ],
          name: "haveToPayPenalties",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
          ],
          name: "isAcceptableContract",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
          ],
          name: "isActiveContract",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "allowedWallet",
              type: "address",
            },
          ],
          name: "isAllowedWallet",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
          ],
          name: "isLesseAcceptable",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_Propiedad",
              type: "uint256",
            },
          ],
          name: "isLessee",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_Propiedad",
              type: "uint256",
            },
          ],
          name: "isOwner",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
          ],
          name: "isOwnerAcceptable",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_Lesse",
              type: "address",
            },
          ],
          name: "isValidLesse",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "mapUsuarioContrato",
          outputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "enum ContractStatus",
              name: "Status",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "Owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "Lesse",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "Monto",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "ID_propiedad",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "AllowedWallet",
              type: "address",
            },
            {
              internalType: "enum PenaltyType",
              name: "Penalty",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "PenaltyPercentage",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "GracePeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "DurationInMonths",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "TimestampLastPayment",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "usuario",
              type: "address",
            },
          ],
          name: "obtenerContratos",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "enum ContractStatus",
                  name: "Status",
                  type: "uint8",
                },
                {
                  internalType: "address",
                  name: "Owner",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "Lesse",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "Monto",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "ID_propiedad",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "AllowedWallet",
                  type: "address",
                },
                {
                  internalType: "enum PenaltyType",
                  name: "Penalty",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "PenaltyPercentage",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "GracePeriod",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "DurationInMonths",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "TimestampLastPayment",
                  type: "uint256",
                },
              ],
              internalType: "struct YourContract.ContratoAlquiler[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_Id",
              type: "uint256",
            },
          ],
          name: "ownerProposedCancelation",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "propiedadesAlquiladas",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_Propiedad",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newMonto",
              type: "uint256",
            },
          ],
          name: "proponerCambios",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_Id",
              type: "uint256",
            },
          ],
          name: "proposeContractCancelationMutualAgreementLessee",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_Id",
              type: "uint256",
            },
          ],
          name: "proposeContractCancelationMutualAgreementOwner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_ID",
              type: "uint256",
            },
          ],
          name: "rentPaidThisMonth",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_propiedad",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newMonto",
              type: "uint256",
            },
          ],
          name: "reviewProposedChanges",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ID_propiedad",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
